Route104_West_MapScripts::
	.byte 0

Route104_West_EventScript_Sign::
	msgbox Route104_West_Text_Sign, MSGBOX_SIGN
	end

Route104_West_Text_Sign:
	.string "Remember to pay attention to your\n"
	.string "surroundings\p"
	.string "Secret passages are often hidden, but\n"
	.string "there's always an indication.\p"
	.string "Like an item lying a few steps behind\n"
	.string "a seemingly impassable tree wall."
